version: "3"

networks:
  swoole:

services:
  composer_laravel:
    image: composer
    volumes:
      - ./laravel:/app
    command: composer install
  php_laravel:
    build: ./laravel
    restart: always
    ports:
      - "80:80"
    networks:
      - swoole

  composer_licence:
    image: composer
    volumes:
      - ./licence:/app
    command: composer install
  php_licence:
    build: ./licence
    restart: always
    ports:
      - "83:80"
    networks:
      - swoole

  composer_organization:
    image: composer
    volumes:
      - ./organization:/app
    command: composer install
  php_organization:
    build: ./organization
    restart: always
    ports:
      - "84:80"
    networks:
      - swoole

  composer_security:
    image: composer
    volumes:
      - ./security:/app
    command: composer install
  php_security:
    build: ./security
    restart: always
    ports:
      - "85:80"
    networks:
      - swoole
  mysql-swoole:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: swoole
      MYSQL_USER: swoole
      MYSQL_PASSWORD: swoole
      MYSQL_ROOT_PASSWORD: swoole
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - swoole
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - swoole